name: Run Tests

on: [push, pull_request]

jobs:
  cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install cmake g++ -y
      - run: |
          cd cpp && mkdir -p build && cd build
          cmake ..
          make
          ./run_tests

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: pip install -r requirements.txt
      - run: pytest python/tests
